name: Tests

on:
  workflow_run:
    workflows: ['Run Tests']
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Download Results
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           mkdir -p test-results && cd test-results

           artifacts_url=${{ github.event.workflow_run.artifacts_url }}

           gh api "$artifacts_url" -q '.test-results[] | [.name, .archive_download_url] | @tsv' | while read artifact
           do
             IFS=$'\t' read name url <<< "$artifact"
             gh api $url > "$name.zip"
             unzip -d "$name" "$name.zip"
           done
 
      - name: Report Test Results
        uses: xibz/nunit-reporter@v1.0.12
        if: always()
        with:
          reportTitle: Anvil
          path: test-results/**/*.xml"
          access-token: ${{ secrets.GITHUB_TOKEN }}
